name: tipitaka_myanmar
description: Burmese transltion of tipitaka pali.

publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_widget_from_html_core: ^0.8.4
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  path: ^1.8.0
  freezed_annotation: ^1.1.0
  provider: ^6.0.2
  sqflite_common_ffi: ^2.1.0+2
  sharedpreference: ^0.0.1
  grouped_list: ^4.1.0
  toggle_switch: ^1.3.0
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
  - assets/database/tipitaka_myanmar.db
  - assets/books/
  - assets/web/

